### ISSUE TITLE
Possible Rounding Bug?

### ISSUE THREAD

**Issue by ThornyJohn** [TekNoLogic/picoGuild#2]
I'm a member of a very small guild, so it takes us a long time to level the guild. I noticed that as soon as the guild passed a small way into level 3.9 picoguild already began showing the guild level as 4.0. Even though it took us three more days to go from level 3.9 to level 4.0, the level was showing as 4.0 all this time. Possibly a rounding error?

**Comment by tekkub** [comment]
Seems string.format rounds instead of truncating

Closed by 98642928a7bb137557e341fd9b3126f55f0d770f
