### ISSUE TITLE
Show Grouped Guildmates

### ISSUE THREAD

**Issue by coliyeah** [TekNoLogic/picoGuild#3]
When forming up guild groups it is immensely helpful to know who's missing at a glance.  Below is a diff for a very simple change to insert a new column and populate it with the @ symbol if the unit is in your group/raid.  Note:  Because you are always in your group, you will always have the symbol by your name.  I didn't feel it necessary to detect this.

99c99
## < local tip = LibStub("tektip-1.0").new(7, "LEFT", "LEFT", "CENTER", "RIGHT", "RIGHT", "RIGHT")

> local tip = LibStub("tektip-1.0").new(6, "LEFT", "LEFT", "CENTER", "RIGHT", "RIGHT", "RIGHT")
> 121,123c121,122
> <               local grouped =((UnitInParty(name) or UnitInRaid(name)) and true) and "@" or ""
> <               tip:AddMultiLine(grouped, (level < 10 and "0" or "")..level, name, area or "???", note, officernote, rank,
> ## <                   1,1,0, lr,lg,lb, cc.r,cc.g,cc.b, ar,ag,ab, nil,nil,nil, 1,1,0, .7,.7,1)
> 
> ```
>           tip:AddMultiLine((level < 10 and "0" or "")..level, name, area or "???", note, officernote, rank,
>               lr,lg,lb, cc.r,cc.g,cc.b, ar,ag,ab, nil,nil,nil, 1,1,0, .7,.7,1)
> ```

**Comment by coliyeah** [comment]
Okay, should have previewed.  That diff didn't parse too well.  Trying again!

```
99c99
< local tip = LibStub("tektip-1.0").new(7, "LEFT", "LEFT", "CENTER", "RIGHT", "RIGHT", "RIGHT")
---
> local tip = LibStub("tektip-1.0").new(6, "LEFT", "LEFT", "CENTER", "RIGHT", "RIGHT", "RIGHT")
121,123c121,122
<               local grouped =((UnitInParty(name) or UnitInRaid(name)) and true) and "@" or ""
<               tip:AddMultiLine(grouped or "", (level < 10 and "0" or "")..level, name, area or "???", note, officernote, rank,
<                   1,1,0, lr,lg,lb, cc.r,cc.g,cc.b, ar,ag,ab, nil,nil,nil, 1,1,0, .7,.7,1)
---
>               tip:AddMultiLine((level < 10 and "0" or "")..level, name, area or "???", note, officernote, rank,
>                   lr,lg,lb, cc.r,cc.g,cc.b, ar,ag,ab, nil,nil,nil, 1,1,0, .7,.7,1)
```

**Comment by tekkub** [comment]
Diffs suck, fork it and send a pull request.
